# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "JSON"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.json"
      - ".github/actions/pdm-*.yml"
      - ".github/workflows/json.yml"
      - ".github/workflows/json-reusable.yml"
      - ".github/workflows/run-*reusable.yml"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  json:
    name: "JSON"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/json-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
