# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "pre-commit Update"

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-update:
    name: "pre-commit Update"
    permissions:
      contents: "read"
      pull-requests: "write"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/pre-commit-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      pull-request: true
...
