# SPDX-FileCopyrightText: Â© 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Typing Renovate"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  cancel-in-progress: true
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}

jobs:
  typing-renovate:
    name: "Typing Renovate"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-typing'
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/typing-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
